# Generated by Django 3.0.5 on 2020-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminBlog', '0002_auto_20200506_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Khác', 'Khác'), ('Nam', 'Nam'), ('Nữ', 'Nữ')], default='Khác', max_length=20),
        ),
    ]
