# Generated by Django 3.0.5 on 2020-05-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='sapo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
