# Generated by Django 3.0.5 on 2020-05-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminBlog', '0003_auto_20200522_1333'),
        ('home', '0002_postmodel_sapo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='adminBlog.UserProfile'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, to='home.CategoryModel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='medias')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PostModel')),
            ],
        ),
    ]
