# Generated by Django 3.0.5 on 2020-04-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
