# Generated by Django 3.0.5 on 2020-05-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200522_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='post',
        ),
    ]
